version: '3'
services:
  resto-server:
    build: ./serverVue
    container_name: resto-server
    ports:
      - 5000:5000
    networks:
      - resto-network

  resto-app:
    build: ./RestauVue
    container_name: resto-app
    networks:
       - resto-network

  rp:
    container_name: restau-docker_rp
    image: nginx
    ports:
       - "49161:80"
    volumes: 
       - ./nginx/:/etc/nginx/conf.d
    networks:
      - resto-network

networks:
  resto-network:
        driver: bridge
