version: '3'
services:
  resto-server:
    build: ./serverVue
    container_name: resto-server
    ports:
      - 5000:5000
    networks:
      - resto-network

  resto-app:
    build: ./RestauVue
    container_name: resto-app
    networks:
      - resto-network

  rp:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - resto-server
      - resto-app
    networks:
      - resto-network

networks:
  resto-network:
